export const STRINGS = {
  aHundredHectares: '100 hectares',
  aThousandTrees: '1,000 trees',
  cocoParque: 'Coco Park, Panama City',
  createAProposal: 'Create a proposal for your local park',
  contribute: 'Contribute',
  contributeETH: 'Contribute ETH to the project and get $PARK tokens in return.',
  contributeHere: 'Contribute here',
  enjoyPark: 'Enjoy a new public park with your friends in your neighborhood!',
  enterETHAmount: 'Enter the ETH amount',
  firstPark: 'First park',
  firstParkLocation: 'Located in the center of downtown Panama City',
  helpUsReachOurGoal: 'Help us reach our goal',
  howDoWeDoThis: 'How do we do this?',
  howMuchWouldYouLikeToContribute: 'How much would you like to contribute?',
  invest: 'Invest',
  itHas: 'It has:',
  localCommunityInitiative: 'Local community initiative has committed to taking care of it after purchase',
  onlyETH: 'We\'re currently only accepting ETH, but plan to add more cryptocurrencies in the future.',
  ourFirstPark: 'Our First Park',
  ourFirstParkDetails: 'Coco Parque is the first ever experiment of its kind - where citizens pool in funds to collectively purchase a park in Panama City.',
  park: 'Park',
  parkName: 'What\'s the name of the park you want to purchase?',
  parkNamePlaceholder: 'Parque Omar',
  privateParks: 'Private Parks',
  progressUpdate: 'We are 65% along the way. 16 ETH to go 🚀.',
  proposalDescription: 'Make your full-on pitch on why this should be our next venture',
  proposalDescriptionPlaceholder: 'This park will completely transform the community of Coco del Mar through it\'s running track, community garden, and dome space.',
  proposalTLDR: 'Give us a TLDR on where this park is located and what is the expected cost',
  proposalTLDRPlaceholder: 'Location: Coco del Mar, Panama City. Cost: 120k USD',
  public: 'Public',
  reviewProposals: 'Review Proposals',
  selectPark: 'Select the park we want to collectively purchase and turn public.',
  submitProposal: 'Submit Proposal',
  teamWork: 'Team Work',
  together: 'Together',
  vote: 'Vote',
  weDecide: "We Decide",
  weTurn: 'We Turn'
}
